---
- name: "Set up a Matrix server"
  hosts: "{{ target if target is defined else 'matrix_servers' }}"
  become: true

  vars_files:
    - roles/matrix-synapse/vars/workers.yml

  roles:
    - matrix-base
    - matrix-dynamic-dns
    - matrix-mailer
    - matrix-postgres
    - matrix-redis
    - matrix-bridge-mautrix-signal
    - matrix-bridge-mautrix-telegram
    - matrix-bridge-mautrix-whatsapp
    - matrix-bridge-mautrix-discord
    - matrix-synapse
    - matrix-dendrite
    - matrix-synapse-admin
    - matrix-prometheus-node-exporter
    - matrix-prometheus-postgres-exporter
    - matrix-prometheus
    - matrix-grafana
    - matrix-registration
    - matrix-jitsi
    - matrix-sygnal
    - matrix-coturn
    - matrix-aux
    - matrix-postgres-backup
    - matrix-backup-borg
    - matrix-common-after
